version: '3.8'

services:
  ngrok:
    image: ngrok/ngrok:latest
    command: http app:5000
    environment:
      - NGROK_AUTHTOKEN=**Top Secret**
    ports:
      - "4040:4040"

  app:
    build: .
    container_name: strava_blockchain_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    depends_on:
      - ngrok
    volumes:
      - ./storage:/app/storage
